using QueueArrayBased.Models;

var queue = new ArrayBasedQueue();

queue.Enqueue("A");
queue.Enqueue("B");
queue.Enqueue("C");
queue.Dequeue();
queue.Dequeue();
queue.Enqueue("D");
queue.Dequeue();
queue.Enqueue("E");
queue.Enqueue("F");
queue.Enqueue("G");
queue.Enqueue("H");
queue.Enqueue("I");
queue.Dequeue();
queue.Dequeue();
queue.Enqueue("J");
queue.Enqueue("K");
queue.Enqueue("L");
queue.Enqueue("M");
queue.Enqueue("N");
queue.Enqueue("O");
queue.Dequeue();
queue.Dequeue();
queue.Dequeue();
queue.Dequeue();
queue.Dequeue();
queue.Enqueue("P");
queue.Enqueue("Q");
queue.Enqueue("R");
queue.Enqueue("S");
queue.Enqueue("T");
queue.Enqueue("U");
queue.Enqueue("V");
queue.Enqueue("W");
queue.Dequeue();
queue.Enqueue("X");
queue.Enqueue("Y");
queue.Enqueue("Z");